theme: jekyll-theme-minimal
title: Open Source Software Business Models
description: Pace of innovation is mostly driven by the community involved in it
logo: osi_logo.png
google_analytics: UA-186307554-1
